# Generated by Django 6.0.4 on 2026-05-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(unique=True)),
                (
                    "scrape_type",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-detect"),
                            ("rss", "RSS Feed"),
                            ("web", "Web Scrape (Playwright)"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("requires_login", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("should_translate", models.BooleanField(default=False)),
                (
                    "source_language",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'sv' for Swedish",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        default="en", help_text="e.g. 'en' for English", max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("argos", "Local Offline (Argos Translate)"),
                            ("deep", "External Backup (Deep Translator)"),
                        ],
                        default="argos",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=50, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="news.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, null=True)),
                ("link", models.URLField(unique=True)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.category",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.source"
                    ),
                ),
            ],
        ),
    ]
