# Generated by Django 6.0.5 on 2026-05-06 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="If blank, this is a global source for everyone.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
