# Generated by Django 6.0.5 on 2026-05-08 14:36

from django.db import migrations


def create_default_data(apps, schema_editor):
    TranslationSetting = apps.get_model('news', 'TranslationSetting')
    Category = apps.get_model('news', 'Category')
    Source = apps.get_model('news', 'Source')

    # Default TranslationSetting
    if not TranslationSetting.objects.exists():
        TranslationSetting.objects.create(engine='argos', is_active=True)

    # Default Category
    category, _ = Category.objects.get_or_create(name="Cybersecurity")

    # Default Source (Bleeping Computer)
    Source.objects.get_or_create(
        name="Bleeping Computer",
        defaults={
            'url': 'https://www.bleepingcomputer.com/feed/',
            'scrape_type': 'rss',
            'should_translate': False,
        }
    )

def remove_default_data(apps, schema_editor):
    TranslationSetting = apps.get_model('news', 'TranslationSetting')
    Category = apps.get_model('news', 'Category')
    Source = apps.get_model('news', 'Source')

    TranslationSetting.objects.all().delete()
    Category.objects.filter(name="Cybersecurity").delete()
    Source.objects.filter(name="Bleeping Computer").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_source_user"),
    ]

    operations = [
        migrations.RunPython(create_default_data, remove_default_data),
    ]
