# Generated by Django 6.0.5 on 2026-05-08 14:38

from django.db import migrations


def create_default_periodic_tasks(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Schedule: Every 15 minutes
    schedule_15_min, _ = CrontabSchedule.objects.get_or_create(
        minute='*/15',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Task: catchup_scrapers
    PeriodicTask.objects.get_or_create(
        crontab=schedule_15_min,
        name='Catchup Scrapers (Every 15 mins)',
        task='apps.news.tasks.catchup_scrapers',
        defaults={'enabled': True}
    )

    # Schedule: Daily at 03:00 UTC
    schedule_03_00, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='3',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Task: run_all_scrapers (03:00 UTC)
    PeriodicTask.objects.get_or_create(
        crontab=schedule_03_00,
        name='Run All Scrapers (03:00 UTC)',
        task='apps.news.tasks.run_all_scrapers',
        defaults={'enabled': True}
    )

    # Schedule: Daily at 05:00 UTC
    schedule_05_00, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='5',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Task: run_all_scrapers (05:00 UTC)
    PeriodicTask.objects.get_or_create(
        crontab=schedule_05_00,
        name='Run All Scrapers (05:00 UTC)',
        task='apps.news.tasks.run_all_scrapers',
        defaults={'enabled': True}
    )


def remove_default_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(
        task__in=[
            'apps.news.tasks.catchup_scrapers',
            'apps.news.tasks.run_all_scrapers'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_default_data"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_default_periodic_tasks, remove_default_periodic_tasks),
    ]
