# Generated by Django 6.0.5 on 2026-05-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DadJokeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retry_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of times to retry fetching a new joke if we receive a duplicate ID.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dad Joke Settings",
                "verbose_name_plural": "Dad Joke Settings",
            },
        ),
        migrations.CreateModel(
            name="Joke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_id",
                    models.CharField(
                        help_text="The ID provided by the icanhazdadjoke API",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "date_used",
                    models.DateField(
                        blank=True,
                        help_text="The date this was used as the Joke of the Day",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JokeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_thumbs_up",
                    models.BooleanField(
                        help_text="True for thumbs up, False for thumbs down"
                    ),
                ),
                ("rated_at", models.DateTimeField(auto_now=True)),
                (
                    "joke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="dadjokes.joke",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joke_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "joke")},
            },
        ),
        migrations.CreateModel(
            name="JokeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "joke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="dadjokes.joke",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joke_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "joke")},
            },
        ),
    ]
