# Generated by Django 6.0.5 on 2026-05-08 14:37

from django.db import migrations


def create_default_data(apps, schema_editor):
    DadJokeSettings = apps.get_model('dadjokes', 'DadJokeSettings')

    if not DadJokeSettings.objects.exists():
        DadJokeSettings.objects.create(retry_limit=5)

def remove_default_data(apps, schema_editor):
    DadJokeSettings = apps.get_model('dadjokes', 'DadJokeSettings')
    DadJokeSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_data, remove_default_data),
    ]
