# Generated by Django 6.0.5 on 2026-05-08 14:40

from django.db import migrations


def create_default_periodic_tasks(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Schedule: Daily at 00:00 UTC
    schedule_00_00, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='0',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Task: fetch_joke_of_the_day
    PeriodicTask.objects.get_or_create(
        crontab=schedule_00_00,
        name='Fetch Joke of the Day (00:00 UTC)',
        task='apps.dadjokes.tasks.fetch_joke_of_the_day',
        defaults={'enabled': True}
    )

def remove_default_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(task='apps.dadjokes.tasks.fetch_joke_of_the_day').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0002_default_data"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_default_periodic_tasks, remove_default_periodic_tasks),
    ]
