# Generated by Django 6.0.5 on 2026-05-08 14:39

from django.db import migrations


def create_default_periodic_tasks(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Schedule: Every minute
    schedule_every_minute, _ = CrontabSchedule.objects.get_or_create(
        minute='*',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Task: process_notifications
    PeriodicTask.objects.get_or_create(
        crontab=schedule_every_minute,
        name='Process Notifications (Every minute)',
        task='apps.notifications.tasks.process_notifications',
        defaults={'enabled': False}
    )

def remove_default_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(task='apps.notifications.tasks.process_notifications').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_default_periodic_tasks, remove_default_periodic_tasks),
    ]
